---

- hosts: all
  become: true
  tasks:

  #- name: Update 
  #  apt:
  #    update_cache: yes
  #  when: ansible_distribution in ["Ubuntu","Dabian"]

  - name: Install Apache2 and php support Packadges
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  
  

  
  - name: Install Apache and php Packadges
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
  
